output_root: '../'
model_path: "/home/ubuntu/kartik/STEGO/saved_models/cocostuff27_vit_base_5.ckpt"
image_dir: "/home/ubuntu/kartik/STEGO/datasets/potsdam/imgs_custom"
experiment_name: "cocostuff_val"
res: 320
batch_size: 8
num_workers: 24
use_ddp: False

hydra:
  run:
    dir: "."
  output_subdir: ~
  #job_logging: "disabled"
  #hydra_logging: "disabled"
