output_root: '../'
pytorch_data_dir: '/home/ubuntu/kartik/STEGO/datasets'
experiment_name: "quicktest"
res: 320
batch_size: 1
num_workers: 24
run_picie: False
run_crf: True
run_prediction: True
dark_mode: True
use_ddp: False

model_paths:
  # - "/home/ubuntu/kartik/STEGO/saved_models/cocostuff27_vit_base_5.ckpt"
  - "/home/ubuntu/kartik/datasets/checkpoints/cocostuff27/directory_exp1_date_Jun23_05-30-29/epoch=0-step=768.ckpt"
  #- "../saved_models/cityscapes_vit_base_1.ckpt"
  #- "../saved_models/potsdam_test.ckpt"

hydra:
  run:
    dir: "."
  output_subdir: ~
  #job_logging: "disabled"
  #hydra_logging: "disabled"
