output_root: '../'
pytorch_data_dir: '/home/ubuntu/kartik/STEGO/datasets'
experiment_name: "quicktest"
pretrained_model: False
res: 320
batch_size: 1
num_workers: 24
run_picie: False
run_crf: True
run_prediction: True
dark_mode: True
use_ddp: False


model_paths:
  - "/home/ubuntu/kartik/datasets/checkpoints/cocostuff27/crop.ckpt"
  # - "/home/ubuntu/kartik/datasets/checkpoints/cocostuff27/epoch=1-step=4992.ckpt"
  #- "../saved_models/cityscapes_vit_base_1.ckpt"
  #- "../saved_models/potsdam_test.ckpt"

hydra:
  run:
    dir: "."
  output_subdir: ~
  #job_logging: "disabled"
  #hydra_logging: "disabled"
